- hosts: all
  become: true
  vars:
    
    value: yes
    

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: "{{value}}"
      update_cache: "{{value}}"
      #cache_valid_time: 86400 
