- hosts: all
  become: true
  vars:
    software: nginx
    value: yes
    service-status: started

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: "{{value}}"
      update_cache: "{{value}}"
      #cache_valid_time: 86400 
  - name: installing "{{software}}" software
    apt:
      name: "{{software}}"
      state: present

  - name: start "{{software}}" service
    service:
      name: "{{software}}"
      state: "{{service-status}}"