- hosts: webservers #here ensure that node instance 
  become: true
  tasks:
   - name: Update and upgrade apt packages
     apt:
      upgrade: yes
      update_cache: yes
      #cache_valid_time: 86400 
   - name: Install apache2 using Ansible Playbook
     package:
      name: apache2
      state: present

   - name: Start apache2 service
     service:
      name: apache2
      state: started
      enabled: yes